CREATE TABLE CUSTOMERS (
  ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(30)
);

CREATE TABLE ROOMS (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  PRICE FLOAT,
  ROOM_TYPE VARCHAR(30),
  CONSTRAINT CHK_TYPE CHECK (ROOM_TYPE IN ('Single', 'Double')),
  CONSTRAINT CHK_PRICE CHECK (PRICE IN ('100','200'))
);

CREATE TABLE BOOKINGS (
  ID  BIGINT PRIMARY KEY AUTO_INCREMENT,
  CUSTOMER_ID BIGINT,
  ROOM_ID BIGINT ,
  FROM_DATE DATE,
  TO_DATE DATE,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
  FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID)
);


