CREATE TABLE HOTELS (
  ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR (30),
  ADDRESS VARCHAR (100)
);

CREATE TABLE ROOMS (
  ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
  HOTEL_ID BIGINT,
  PRICE FLOAT,
  TYPE VARCHAR (30),
  FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS(ID)
);

CREATE TABLE USERS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR (30),
  PASSWORD VARCHAR (30)
);

CREATE TABLE AUTHORITIES(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  USERNAME varchar(30),
  AUTHORITY varchar(30)
);